DEFAULT_FONT = 'meiryo'

class SidebarFont:
    BUTTON = (DEFAULT_FONT, 15)

class TopFrameFont:
    TITLE = (DEFAULT_FONT, 70)
    TAB_BUTTON = (DEFAULT_FONT, 15)
    DESCRIPTION = (DEFAULT_FONT, 18)
    TEXT_BOX = (DEFAULT_FONT, 18)
    MAIN_BUTTON = (DEFAULT_FONT, 20)

class ChatFrameFont:
    INPUT_TEXT = (DEFAULT_FONT, 17)
    MESSAGE_TEXT = (DEFAULT_FONT, 12)