class ImageSize:
    WIDTH = 200
    HEIGHT = 200

class SidebarButtonSize:
    WIDTH = 60
    HEIGHT= 60

class TopFrameSize:
    TAB_WIDTH = 550
    TAB_HEIGHT = 330
    TEXT_BOX_WIDTH = 550
    TEXT_BOX_HEIGHT = 170
    MAIN_BUTTON_WIDTH = 320
    MAIN_BUTTON_HEIGHT = 50
    GENERATED_IMAGE_WIDTH = 200
    GENERATED_IMAGE_HEIGHT = 200
    CANCEL_BUTTON_WIDTH = 32
    CANCEL_BUTTON_HEIGHT = 32

class ChatPageSize:
    BUTTON_WIDTH = 25
    BUTTON_HEIGHT = 25
    TEXT_BOX_WIDTH = 500
    TEXT_BOX_HEIGHT = 40